### ISSUE TITLE
no such file or directory '/frontier-release/dist/images/favicon.png'

### ISSUE THREAD

**Issue by brucedaniel** [ethereum/frontier-release#101]
Workaround:

ln -s public/ dist

Error:

fs.js:797
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/frontier-release/dist/images/favicon.png'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at favicon (/frontier-release/node_modules/serve-favicon/index.js:64:15)
    at Object.<anonymous> (/frontier-release/app.js:13:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by cubedro** [comment]
did you run grunt?
